global:
  resolve_timeout: 60m
route:
  group_by: ['alertname']
  receiver: empty
  routes:
    - receiver: discord_webhook_mainnet
      group_wait: 100ms
      group_interval: 100ms
      repeat_interval: 1h
      matchers:
        - network="mainnet"

receivers:
  - name: 'empty'
  - name: 'discord_webhook_mainnet'
    webhook_configs:
      - url: 'http://alertmanager-discord:5001/hook/head-watcher'
        send_resolved: false
