---
name: Build Docker image

on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop
      - master
    paths-ignore:
      - ".github/**"
      - "README.md"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build image
        uses: docker/build-push-action@v4
        with:
          tags: app:ci
          push: false
